# Based off GitHub defaults
# https://help.github.com/articles/configuring-jekyll/#defaults-you-can-change
# github: [metadata]

# GitHub sets these--and they cannot be changed there
# https://help.github.com/articles/configuring-jekyll/#configuration-settings-you-cannot-change
lsi: false
safe: true
repository: https://github.com/rdfa/rdfa.github.io
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
